name: GSA_workshop
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy = 1.21.5
  - matplotlib = 3.5.1
  - ipywidgets = 7.6.5
  - scipy = 1.7.3
  - numba = 0.55.1
  - pip:
    - git+https://github.com/valnoacco/SAFE_workshop_UCL/tree/main/SAFE-python
